// rules = [
// 	["dark olive", "muted brown", "mirrored tomato", "bright black"],
// 	["faded coral", "drab cyan", "light aqua"],
// 	["plaid plum", "mirrored cyan"],
// 	["clear maroon", "dotted turquoise", "dim lavender"],
// 	["plaid coral", "posh fuchsia", "dotted beige", "wavy turquoise"],
// 	["mirrored indigo", "pale orange", "striped aqua", "dotted cyan", "muted coral"],
// 	["striped brown", "faded green", "vibrant red", "drab black", "dark orange"],
// 	["drab fuchsia", "shiny chartreuse", "dark orange", "drab blue", "bright chartreuse"],
// 	["light fuchsia", "bright gold", "clear indigo"],
// 	["plaid olive", "striped indigo", "muted olive", "light gray", "wavy purple"],
// 	["dotted green", "faded yellow"],
// 	["dotted cyan", "light red", "dark cyan"],
// 	["muted magenta", "clear plum"],
// 	["mirrored cyan", "bright lavender", "mirrored gold", "plaid silver", "posh chartreuse"],
// 	["muted red", "wavy olive", "shiny cyan"],
// 	["clear indigo", "dotted magenta", "bright silver", "muted aqua"],
// 	["plaid chartreuse", "dark chartreuse", "faded lavender"],
// 	["wavy tan", "light red"],
// 	["bright crimson", "pale magenta"],
// 	["pale yellow", "clear plum", "vibrant cyan", "muted white"],
// 	["pale tomato", "muted red"],
// 	["dull salmon", "dark gold"],
// 	["light white", "drab chartreuse"],
// 	["drab plum", "dark brown"],
// 	["shiny purple", "pale brown", "bright crimson", "muted teal"],
// 	["pale red", "posh cyan", "drab cyan"],
// 	["dull bronze", "striped indigo", "plaid black", "clear violet", "dull chartreuse"],
// 	["wavy indigo", "dull coral", "dark tan"],
// 	["vibrant silver", "muted aqua"],
// 	["shiny tan", "pale beige", "bright gold", "muted coral", "shiny red"],
// 	["dim yellow", "dotted chartreuse"],
// 	["faded white", "posh lavender", "bright silver", "dark green", "muted lavender"],
// 	["shiny tomato", "mirrored chartreuse", "bright yellow", "vibrant plum"],
// 	["dark yellow", "plaid lime", "wavy lavender"],
// 	["dim magenta", "wavy violet"],
// 	["striped white", "striped chartreuse"],
// 	["muted gray", "muted brown", "light lavender", "clear gold", "shiny green"],
// 	["drab white", "muted yellow", "posh lavender", "faded fuchsia"],
// 	["dark lime", "bright crimson"],
// 	["muted salmon", "dull red", "dull violet"],
// 	["muted black", "vibrant black", "pale tomato"],
// 	["plaid white", "drab black", "drab cyan", "dim olive"],
// 	["clear green", "wavy purple", "pale gold"],
// 	["drab orange", "clear maroon", "vibrant gold"],
// 	["light salmon", "pale black", "posh fuchsia"],
// 	["faded tomato", "faded black", "vibrant coral", "bright brown"],
// 	["dull green", "clear lime"],
// 	["dim orange", "posh red", "dim gray", "muted gold"],
// 	["dotted orange", "faded tan", "drab tomato"],
// 	["dull gold", "muted gold"],
// 	["clear beige", "plaid tan", "dim maroon"],
// 	["mirrored bronze", "clear blue", "clear tan", "clear orange"],
// 	["shiny brown", "light tomato"],
// 	["pale cyan", "dull silver"],
// 	["muted purple", "posh brown"],
// 	["pale maroon", "clear maroon", "vibrant yellow", "shiny violet"],
// 	["muted green", "plaid plum"],
// 	["light coral", "bright lime", "dotted indigo", "shiny bronze"],
// 	["wavy beige", "light magenta", "pale lime", "faded yellow"],
// 	["wavy turquoise", "shiny red", "mirrored yellow", "posh bronze"],
// 	["pale brown", "striped salmon", "vibrant plum", "dull silver"],
// 	["striped bronze", "posh black", "bright yellow", "dotted silver", "mirrored violet"],
// 	["pale tan", "shiny lavender", "dotted turquoise", "pale turquoise", "plaid white"],
// 	["muted crimson", "dull lime", "pale magenta", "light cyan"],
// 	["dotted purple", "wavy magenta"],
// 	["dull black", "light crimson", "mirrored fuchsia", "posh lime"],
// 	["mirrored aqua", "dark brown", "pale gold", "pale purple", "vibrant crimson"],
// 	["shiny beige", "muted indigo", "dark tan"],
// 	["shiny aqua", "vibrant tan", "pale tomato", "faded blue", "pale magenta"],
// 	["mirrored lavender", "faded yellow", "light chartreuse", "dull crimson", "pale aqua"],
// 	["faded gray", "bright yellow", "light silver"],
// 	["light tan", "bright fuchsia", "light crimson", "clear olive", "clear silver"],
// 	["dull crimson", "wavy olive", "light maroon"],
// 	["pale olive", "vibrant purple", "clear fuchsia", "pale tan"],
// 	["dim beige", "dull silver"],
// 	["dark bronze", "mirrored orange", "wavy crimson", "dark maroon"],
// 	["mirrored fuchsia", "dark chartreuse", "dotted bronze", "shiny silver"],
// 	["striped tomato", "dark fuchsia", "vibrant maroon", "drab crimson"],
// 	["muted chartreuse", "light tomato", "light magenta", "dull beige"],
// 	["muted violet", "light tomato"],
// 	["dim violet", "mirrored purple", "bright black", "vibrant plum"],
// 	["muted beige", "muted plum", "mirrored gold", "bright yellow"],
// 	["shiny coral", "vibrant gray", "light bronze", "faded chartreuse", "plaid violet"],
// 	["dotted yellow", "dotted turquoise"],
// 	["faded bronze", "dull purple", "pale fuchsia"],
// 	["clear fuchsia", "bright yellow"],
// 	["dotted beige", "pale turquoise"],
// 	["bright aqua", "faded silver", "dim fuchsia"],
// 	["dim silver", "wavy brown", "light maroon", "wavy black"],
// 	["plaid tan", "dotted green"],
// 	["drab teal", "mirrored violet", "dotted bronze", "pale cyan"],
// 	["plaid yellow", "shiny magenta", "dark silver", "shiny indigo", "faded gray"],
// 	["dull cyan", "posh plum", "dim coral"],
// 	["pale beige", "dark cyan", "faded tan", "plaid silver"],
// 	["faded salmon", "light olive", "dark tan"],
// 	["bright silver", "clear fuchsia", "clear lime"],
// 	["dark lavender", "pale cyan", "dotted salmon", "striped turquoise", "dim crimson"],
// 	["light gray", "dotted chartreuse", "dull red", "bright gold", "light lime"],
// 	["dark indigo", "shiny coral", "muted teal", "plaid purple", "faded yellow"],
// 	["light maroon", "wavy brown"],
// 	["dotted brown", "clear violet"],
// 	["pale indigo", "wavy brown", "dark olive", "pale black", "striped lavender"],
// 	["pale purple", "bright chartreuse", "vibrant magenta", "clear tomato", "light cyan"],
// 	["dim teal", "dark salmon", "mirrored gold", "bright gold"],
// 	["wavy olive", "vibrant purple", "dull silver"],
// 	["pale aqua", "dark violet", "dark plum", "vibrant brown"],
// 	["muted cyan", "vibrant crimson", "pale magenta"],
// 	["vibrant fuchsia", "light beige", "bright purple", "light maroon", "dull beige"],
// 	["bright blue", "vibrant plum"],
// 	["vibrant green", "dark salmon"],
// 	["dull red", "dotted maroon", "posh salmon", "dotted chartreuse", "dim yellow"],
// 	["dotted magenta", "plaid violet", "light gray"],
// 	["wavy bronze", "posh plum", "bright lavender"],
// 	["shiny orange", "muted plum"],
// 	["plaid bronze", "plaid chartreuse", "mirrored turquoise", "light salmon"],
// 	["shiny yellow", "striped teal", "vibrant maroon", "drab indigo", "muted beige"],
// 	["faded indigo", "posh lime", "vibrant teal"],
// 	["posh tomato", "striped salmon", "drab red"],
// 	["light plum", "bright blue", "dotted black", "shiny brown", "clear tan"],
// 	["pale green", "clear maroon", "dull green", "clear aqua", "drab beige"],
// 	["drab brown", "bright plum", "striped indigo", "vibrant lime"],
// 	["muted lime", "faded tan", "vibrant magenta", "posh coral"],
// 	["faded violet", "posh purple", "muted crimson", "striped red"],
// 	["striped green", "clear chartreuse", "dim maroon", "faded cyan", "faded silver"],
// 	["dim plum", "faded tan", "vibrant crimson", "light gray", "wavy teal"],
// 	["drab cyan", "muted plum", "mirrored black", "clear fuchsia"],
// 	["vibrant lime", "pale brown", "plaid violet"],
// 	["drab purple", "posh turquoise", "clear violet", "faded coral", "striped gold"],
// 	["mirrored gray", "dotted orange", "mirrored tomato", "plaid lime"],
// 	["plaid teal", "dim coral", "shiny magenta", "striped beige"],
// 	["vibrant white", "shiny red", "plaid black"],
// 	["faded crimson", "faded yellow"],
// 	["dim chartreuse", "mirrored teal", "light lavender"],
// 	["wavy magenta", "dark cyan"],
// 	["mirrored magenta", "muted salmon", "pale maroon"],
// 	["plaid silver", "pale turquoise", "posh salmon"],
// 	["bright cyan", "dark orange", "mirrored gold", "light violet", "faded silver"],
// 	["faded orange", "drab red", "dark tan", "vibrant magenta"],
// 	["wavy gold", "drab tomato", "muted yellow"],
// 	["wavy salmon", "dotted bronze", "light white", "dotted brown"],
// 	["posh plum", "drab black", "light silver"],
// 	["dim aqua", "striped black", "bright yellow", "posh salmon", "striped salmon"],
// 	["shiny fuchsia", "dim cyan"],
// 	["dark tan", "dull plum"],
// 	["mirrored red", "pale lime", "dim maroon"],
// 	["bright purple", "posh magenta", "wavy magenta", "posh plum", "dull lime"],
// 	["striped olive", "bright lavender", "mirrored black", "bright gold", "pale plum"],
// 	["dotted bronze", "dull coral", "faded black"],
// 	["shiny green", "shiny indigo"],
// 	["mirrored chartreuse", "no other"],
// 	["pale crimson", "light orange", "light lime", "dotted cyan"],
// 	["shiny lavender", "shiny crimson", "striped tan"],
// 	["wavy blue", "pale brown", "light cyan", "light magenta", "pale tan"],
// 	["muted plum", "dull red", "dotted maroon", "vibrant red", "bright chartreuse"],
// 	["vibrant violet", "dull brown"],
// 	["faded chartreuse", "dotted yellow"],
// 	["drab chartreuse", "shiny gold"],
// 	["posh crimson", "clear cyan", "light crimson", "drab crimson", "clear blue"],
// 	["drab tomato", "striped salmon"],
// 	["clear red", "pale blue", "posh orange", "dark aqua", "posh red"],
// 	["drab lavender", "muted gray"],
// 	["pale blue", "pale beige", "muted green", "shiny white"],
// 	["posh cyan", "clear aqua", "drab chartreuse", "dark purple", "posh salmon"],
// 	["faded silver", "dim salmon", "striped bronze"],
// 	["dim green", "dark fuchsia"],
// 	["plaid aqua", "dim red", "drab turquoise", "dim aqua", "dull salmon"],
// 	["posh fuchsia", "dotted fuchsia"],
// 	["striped lime", "dull silver", "posh black", "dark fuchsia", "dull lime"],
// 	["clear olive", "pale crimson", "shiny orange", "posh magenta", "dark fuchsia"],
// 	["bright lime", "striped tan", "dull plum", "bright yellow"],
// 	["faded green", "pale turquoise", "light lime"],
// 	["plaid indigo", "drab crimson"],
// 	["shiny turquoise", "faded crimson"],
// 	["drab aqua", "mirrored red", "drab gold", "wavy orange"],
// 	["dim gray", "shiny lime", "dotted fuchsia"],
// 	["light teal", "pale beige", "shiny cyan", "striped red", "light orange"],
// 	["wavy red", "dotted tan", "pale aqua"],
// 	["vibrant red", "no other"],
// 	["striped salmon", "no other"],
// 	["clear silver", "shiny orange", "pale aqua", "faded purple", "dim coral"],
// 	["muted tan", "pale maroon", "dotted maroon", "bright plum", "pale teal"],
// 	["faded yellow", "striped black", "dotted chartreuse", "drab chartreuse", "shiny tomato"],
// 	["dark green", "light lime"],
// 	["striped cyan", "posh magenta", "dim cyan"],
// 	["vibrant teal", "dim magenta", "bright chartreuse", "bright tan", "bright yellow"],
// 	["bright red", "posh white"],
// 	["bright magenta", "posh salmon", "dull fuchsia", "posh lavender"],
// 	["bright white", "bright chartreuse", "mirrored yellow"],
// 	["dotted teal", "bright gray", "vibrant fuchsia"],
// 	["clear blue", "pale brown", "drab indigo", "pale salmon", "muted olive"],
// 	["dull brown", "dim cyan", "vibrant plum", "posh chartreuse"],
// 	["vibrant tan", "dark orange"],
// 	["shiny white", "mirrored violet", "drab indigo"],
// 	["clear violet", "vibrant crimson", "light gold", "striped silver"],
// 	["bright coral", "drab blue", "muted olive", "faded purple", "vibrant maroon"],
// 	["dotted aqua", "wavy black", "mirrored gold", "posh red", "plaid silver"],
// 	["clear crimson", "plaid gold"],
// 	["faded fuchsia", "shiny coral", "pale beige"],
// 	["wavy crimson", "dotted turquoise", "light gray", "wavy purple", "faded gray"],
// 	["dark fuchsia", "wavy brown", "vibrant orange"],
// 	["striped plum", "vibrant cyan", "posh lime"],
// 	["shiny salmon", "drab magenta", "mirrored turquoise"],
// 	["dim brown", "shiny gold", "dotted cyan", "plaid cyan"],
// 	["posh violet", "dim red", "posh white", "faded aqua", "shiny gold"],
// 	["pale black", "pale plum"],
// 	["shiny red", "posh salmon", "dotted chartreuse"],
// 	["dull olive", "light blue"],
// 	["bright olive", "striped olive", "muted plum", "striped magenta"],
// 	["posh brown", "vibrant gold", "wavy silver", "dotted salmon", "drab orange"],
// 	["bright tan", "light chartreuse"],
// 	["dull beige", "pale violet"],
// 	["light yellow", "clear indigo", "wavy brown", "bright black", "shiny lime"],
// 	["dull aqua", "dull black", "posh black", "wavy fuchsia"],
// 	["dark gold", "clear fuchsia", "dark cyan", "dark orange"],
// 	["wavy white", "dark brown", "drab yellow", "dotted turquoise", "muted tomato"],
// 	["posh silver", "dim chartreuse", "light fuchsia", "faded purple", "drab cyan"],
// 	["dotted coral", "plaid silver", "posh beige", "dim beige", "vibrant crimson"],
// 	["drab silver", "posh chartreuse"],
// 	["dull teal", "dim indigo"],
// 	["wavy brown", "no other"],
// 	["posh purple", "wavy purple", "muted gold"],
// 	["faded magenta", "wavy aqua", "vibrant beige"],
// 	["vibrant magenta", "wavy black", "shiny maroon", "dim tomato", "vibrant gray"],
// 	["mirrored brown", "light aqua", "clear orange", "bright lavender"],
// 	["light crimson", "posh chartreuse"],
// 	["dotted olive", "dim tomato", "dim plum"],
// 	["light indigo", "bright gold", "drab chartreuse", "dim fuchsia", "vibrant black"],
// 	["vibrant chartreuse", "dim crimson", "clear plum", "striped black"],
// 	["pale violet", "dark salmon"],
// 	["bright violet", "striped aqua"],
// 	["dull maroon", "drab aqua", "mirrored lavender", "dotted brown"],
// 	["dim lime", "wavy salmon", "striped tan"],
// 	["dotted tan", "dull yellow", "shiny violet"],
// 	["posh yellow", "dull crimson", "dim olive", "dark black"],
// 	["dull violet", "bright yellow", "posh magenta", "shiny red"],
// 	["dotted silver", "wavy turquoise", "dull tomato", "bright tan", "dotted salmon"],
// 	["pale gray", "plaid turquoise", "bright salmon"],
// 	["clear purple", "shiny gold", "faded teal"],
// 	["striped tan", "mirrored cyan", "pale beige"],
// 	["dotted indigo", "pale purple", "pale black", "dark salmon"],
// 	["clear turquoise", "light lavender"],
// 	["wavy plum", "shiny aqua"],
// 	["muted indigo", "drab teal"],
// 	["muted yellow", "vibrant cyan", "dim white"],
// 	["dark white", "drab crimson", "dull gray"],
// 	["faded blue", "faded olive", "shiny magenta", "dark plum"],
// 	["posh tan", "posh plum", "muted black", "clear indigo", "striped gold"],
// 	["striped silver", "drab tomato"],
// 	["muted lavender", "dim silver", "wavy lavender", "faded tan"],
// 	["wavy chartreuse", "dull bronze"],
// 	["dark blue", "dotted silver", "light yellow", "mirrored bronze", "shiny lavender"],
// 	["dim turquoise", "pale green", "mirrored gray"],
// 	["muted blue", "striped lavender", "dark fuchsia"],
// 	["faded brown", "dotted violet", "faded indigo", "drab indigo"],
// 	["shiny magenta", "dotted turquoise", "plaid violet", "dim cyan"],
// 	["clear chartreuse", "pale maroon", "plaid blue", "clear tan"],
// 	["faded turquoise", "mirrored magenta"],
// 	["posh turquoise", "dotted yellow", "striped purple", "pale cyan"],
// 	["vibrant tomato", "dark cyan"],
// 	["mirrored white", "mirrored indigo", "dim cyan", "bright lavender"],
// 	["dull purple", "striped yellow", "dull plum", "shiny gold", "pale gold"],
// 	["mirrored yellow", "shiny crimson"],
// 	["posh white", "mirrored orange"],
// 	["wavy fuchsia", "dotted tan", "shiny coral"],
// 	["mirrored green", "dull white", "shiny crimson"],
// 	["plaid turquoise", "pale salmon", "dull beige"],
// 	["clear cyan", "dim silver", "drab chartreuse"],
// 	["mirrored purple", "dull coral", "vibrant plum"],
// 	["dim lavender", "striped black", "shiny red", "posh chartreuse", "dim teal"],
// 	["plaid cyan", "dim orange"],
// 	["plaid magenta", "striped red", "striped salmon"],
// 	["shiny blue", "shiny turquoise", "posh orange"],
// 	["faded aqua", "light yellow", "wavy purple", "dull lime", "dotted black"],
// 	["mirrored blue", "wavy silver"],
// 	["posh indigo", "dark tan", "vibrant blue", "dark bronze", "vibrant crimson"],
// 	["clear plum", "wavy teal", "faded yellow"],
// 	["dark gray", "bright lavender"],
// 	["muted coral", "shiny red", "pale teal", "dim olive", "muted silver"],
// 	["dim gold", "pale gold", "vibrant red"],
// 	["plaid violet", "faded green", "mirrored teal", "wavy purple", "faded yellow"],
// 	["clear tomato", "drab beige", "dim cyan"],
// 	["bright beige", "muted brown", "wavy red", "clear maroon"],
// 	["wavy teal", "muted beige", "posh salmon", "posh black", "dotted maroon"],
// 	["vibrant salmon", "vibrant purple", "dull chartreuse"],
// 	["dull coral", "light red", "dark plum", "bright gray", "dotted cyan"],
// 	["bright turquoise", "plaid teal", "muted orange"],
// 	["wavy maroon", "pale fuchsia", "dotted magenta"],
// 	["plaid gold", "shiny lavender", "vibrant gray", "mirrored teal"],
// 	["wavy black", "wavy magenta"],
// 	["drab beige", "mirrored chartreuse", "wavy brown", "pale beige", "pale turquoise"],
// 	["posh blue", "clear silver"],
// 	["vibrant turquoise", "posh white", "bright gold"],
// 	["faded black", "wavy black", "shiny crimson"],
// 	["pale salmon", "vibrant brown"],
// 	["striped gray", "mirrored violet", "dull violet", "muted turquoise"],
// 	["light brown", "muted crimson", "drab crimson", "muted aqua", "dotted blue"],
// 	["striped turquoise", "muted blue", "mirrored salmon"],
// 	["shiny lime", "vibrant purple", "pale turquoise", "drab tomato", "dotted maroon"],
// 	["dotted white", "pale violet", "posh plum", "shiny chartreuse", "faded bronze"],
// 	["dotted crimson", "shiny olive", "mirrored yellow"],
// 	["mirrored teal", "dull violet", "shiny red", "drab black", "posh magenta"],
// 	["striped lavender", "light crimson"],
// 	["pale chartreuse", "wavy red"],
// 	["posh gray", "posh black"],
// 	["clear teal", "dull violet", "dotted chartreuse", "drab tan"],
// 	["light olive", "muted olive", "plaid turquoise"],
// 	["light tomato", "dull chartreuse", "muted beige"],
// 	["light orange", "wavy lavender"],
// 	["wavy coral", "drab beige", "plaid white"],
// 	["dotted violet", "muted salmon", "shiny red", "shiny crimson"],
// 	["muted fuchsia", "dull coral"],
// 	["pale turquoise", "vibrant red"],
// 	["faded beige", "striped magenta"],
// 	["dull tan", "drab maroon", "muted beige"],
// 	["posh lime", "wavy turquoise", "light blue", "posh salmon"],
// 	["drab magenta", "dim magenta"],
// 	["striped crimson", "dull white", "muted plum", "posh chartreuse"],
// 	["vibrant maroon", "pale aqua"],
// 	["dotted black", "shiny bronze", "shiny lime", "dotted yellow", "wavy turquoise"],
// 	["wavy aqua", "dull tomato", "shiny olive", "vibrant brown", "dim chartreuse"],
// 	["dim tan", "bright plum", "striped gold", "dull coral"],
// 	["dull fuchsia", "wavy maroon"],
// 	["striped red", "shiny red", "clear gold", "posh magenta", "bright yellow"],
// 	["dotted lavender", "faded lavender"],
// 	["muted turquoise", "faded fuchsia"],
// 	["bright gray", "light silver", "dull violet"],
// 	["dull indigo", "dim violet", "plaid salmon", "plaid beige"],
// 	["wavy purple", "dim yellow", "posh salmon"],
// 	["wavy lime", "dark fuchsia", "dark salmon", "bright silver", "pale aqua"],
// 	["light cyan", "clear blue"],
// 	["light beige", "dull red", "dark violet", "shiny lime"],
// 	["mirrored silver", "plaid beige", "dull coral"],
// 	["dark beige", "clear tan", "wavy orange", "shiny cyan", "shiny magenta"],
// 	["vibrant crimson", "mirrored teal", "pale turquoise", "posh magenta"],
// 	["faded red", "plaid lime", "clear brown"],
// 	["dim bronze", "dark beige", "plaid cyan", "clear purple"],
// 	["bright maroon", "light gray", "faded turquoise", "posh cyan"],
// 	["clear gray", "faded green"],
// 	["pale silver", "dull magenta"],
// 	["dotted red", "clear purple", "faded crimson", "dull bronze", "muted plum"],
// 	["striped maroon", "mirrored cyan", "dark green", "clear indigo", "muted beige"],
// 	["dark cyan", "dotted maroon", "vibrant red"],
// 	["clear bronze", "drab lime", "light gold"],
// 	["dull yellow", "dull chartreuse", "muted olive"],
// 	["plaid lavender", "vibrant silver", "clear fuchsia"],
// 	["posh black", "dotted salmon", "drab tomato", "drab black"],
// 	["faded lime", "dark silver"],
// 	["clear lavender", "light violet"],
// 	["dotted gray", "clear lavender", "shiny magenta"],
// 	["shiny gray", "dull brown"],
// 	["drab coral", "faded beige"],
// 	["dark teal", "drab indigo", "light aqua", "faded tan", "wavy brown"],
// 	["shiny violet", "posh black", "dim beige"],
// 	["clear salmon", "clear orange"],
// 	["shiny olive", "shiny yellow", "shiny indigo", "bright yellow"],
// 	["plaid salmon", "striped yellow", "mirrored chartreuse", "light magenta", "mirrored magenta"],
// 	["wavy orange", "vibrant purple"],
// 	["posh magenta", "mirrored chartreuse", "vibrant red"],
// 	["pale fuchsia", "muted silver"],
// 	["light black", "wavy orange", "faded tomato"],
// 	["light gold", "dull red"],
// 	["bright brown", "mirrored beige", "faded indigo"],
// 	["muted teal", "posh magenta", "dim gray", "pale plum"],
// 	["pale plum", "muted beige", "posh magenta", "shiny gold"],
// 	["drab gold", "striped beige"],
// 	["posh gold", "shiny silver"],
// 	["dull turquoise", "vibrant crimson", "faded gray", "muted purple"],
// 	["light chartreuse", "bright lavender", "bright silver"],
// 	["striped chartreuse", "shiny coral", "clear blue", "dotted turquoise"],
// 	["dark aqua", "wavy bronze", "shiny brown", "bright violet", "dotted indigo"],
// 	["muted bronze", "pale salmon", "striped teal"],
// 	["dark violet", "wavy magenta"],
// 	["dark maroon", "muted red"],
// 	["shiny silver", "light gray", "pale aqua", "dim tomato"],
// 	["bright lavender", "striped red", "faded tan"],
// 	["dim olive", "posh cyan", "light aqua", "wavy tan", "dull silver"],
// 	["posh beige", "faded tan", "shiny lime", "wavy lavender"],
// 	["muted maroon", "mirrored purple", "mirrored gold", "clear tan"],
// 	["vibrant yellow", "light lavender"],
// 	["light purple", "faded olive", "wavy red"],
// 	["bright yellow", "dotted salmon", "posh magenta", "striped salmon"],
// 	["dull gray", "posh magenta", "shiny white", "dim bronze", "dim lavender"],
// 	["vibrant plum", "faded tan", "pale turquoise", "bright chartreuse", "dull violet"],
// 	["posh chartreuse", "bright chartreuse", "drab black", "posh magenta", "dark orange"],
// 	["drab gray", "plaid turquoise"],
// 	["dark brown", "dotted green", "dim lavender"],
// 	["mirrored crimson", "light teal", "plaid blue", "wavy red", "bright tomato"],
// 	["dotted gold", "bright olive"],
// 	["dark salmon", "pale turquoise", "faded tan", "mirrored chartreuse"],
// 	["wavy gray", "shiny green", "shiny red"],
// 	["dotted blue", "wavy yellow", "dull beige"],
// 	["dim maroon", "wavy maroon", "dim violet", "dark tan"],
// 	["plaid purple", "dark teal", "mirrored black", "wavy lavender"],
// 	["dull blue", "bright gold", "dim olive", "muted chartreuse", "striped salmon"],
// 	["muted white", "light bronze", "wavy beige"],
// 	["muted gold", "no other"],
// 	["drab green", "plaid chartreuse"],
// 	["clear coral", "mirrored cyan"],
// 	["drab turquoise", "posh black"],
// 	["dotted fuchsia", "light red", "clear aqua", "posh magenta", "vibrant cyan"],
// 	["clear lime", "dark chartreuse"],
// 	["mirrored plum", "wavy tan", "bright olive"],
// 	["vibrant coral", "light gray", "light white"],
// 	["pale bronze", "bright silver", "vibrant tan", "posh lime", "wavy silver"],
// 	["plaid blue", "dotted beige", "wavy olive", "striped tomato"],
// 	["shiny teal", "shiny violet", "faded blue", "shiny white", "dim fuchsia"],
// 	["clear black", "faded purple", "dim tomato", "striped brown", "faded indigo"],
// 	["clear orange", "bright gold", "light crimson", "faded yellow"],
// 	["drab maroon", "vibrant red", "dotted bronze"],
// 	["drab blue", "mirrored aqua", "dark gold", "shiny crimson"],
// 	["striped black", "drab black", "dark orange"],
// 	["light lavender", "clear blue", "striped red"],
// 	["posh bronze", "light red", "dull plum", "dim coral", "clear blue"],
// 	["plaid beige", "dotted turquoise", "light cyan"],
// 	["plaid fuchsia", "wavy fuchsia"],
// 	["shiny bronze", "vibrant silver", "striped silver", "pale turquoise", "faded olive"],
// 	["vibrant purple", "wavy magenta"],
// 	["pale magenta", "dim yellow", "dim aqua"],
// 	["faded purple", "mirrored black", "muted beige", "muted aqua", "light maroon"],
// 	["light turquoise", "muted brown", "posh beige", "vibrant fuchsia", "faded teal"],
// 	["vibrant lavender", "light chartreuse", "mirrored teal", "drab lavender", "shiny brown"],
// 	["striped yellow", "dotted cyan", "mirrored turquoise"],
// 	["drab bronze", "shiny lavender", "muted yellow", "plaid teal", "plaid gold"],
// 	["posh maroon", "bright fuchsia", "dotted indigo", "dark teal", "faded violet"],
// 	["vibrant cyan", "dark orange"],
// 	["striped aqua", "light bronze", "dull beige", "pale violet", "pale beige"],
// 	["faded gold", "pale crimson"],
// 	["muted olive", "mirrored teal", "dim aqua", "posh chartreuse", "dull brown"],
// 	["dim coral", "mirrored gold"],
// 	["dull silver", "faded gray", "light red", "light crimson", "bright chartreuse"],
// 	["vibrant gray", "plaid silver", "plaid violet", "dim silver", "mirrored chartreuse"],
// 	["plaid crimson", "vibrant bronze", "drab olive", "pale purple"],
// 	["dotted maroon", "no other"],
// 	["vibrant brown", "dull violet", "muted beige", "wavy teal"],
// 	["bright tomato", "muted beige"],
// 	["shiny cyan", "clear gold", "shiny lime", "wavy magenta", "wavy lavender"],
// 	["drab tan", "plaid red"],
// 	["dull plum", "dotted magenta", "plaid silver", "pale teal", "dim yellow"],
// 	["clear gold", "bright gold", "dark orange", "posh magenta"],
// 	["shiny gold", "dark salmon", "wavy purple", "dark cyan", "dull chartreuse"],
// 	["mirrored tomato", "light aqua", "pale plum", "pale beige"],
// 	["dim tomato", "light crimson", "bright lavender"],
// 	["mirrored tan", "vibrant plum", "faded violet", "striped lime", "muted white"],
// 	["faded teal", "drab silver"],
// 	["dim red", "clear turquoise", "drab maroon"],
// 	["dark magenta", "clear cyan"],
// 	["vibrant gold", "dotted salmon", "bright chartreuse", "striped purple"],
// 	["muted brown", "posh beige", "muted aqua", "dim beige", "dim magenta"],
// 	["plaid orange", "dark purple", "mirrored tomato", "vibrant orange"],
// 	["pale gold", "vibrant plum", "dotted violet"],
// 	["plaid gray", "bright silver", "drab fuchsia"],
// 	["muted orange", "dull magenta", "clear lavender", "mirrored chartreuse", "vibrant silver"],
// 	["muted aqua", "dim silver", "wavy black"],
// 	["dim crimson", "mirrored bronze", "muted cyan"],
// 	["dark tomato", "pale blue"],
// 	["bright salmon", "vibrant tan", "bright white", "dim gray"],
// 	["mirrored orange", "dark salmon", "drab beige", "dull chartreuse", "shiny cyan"],
// 	["clear aqua", "dim teal", "wavy olive"],
// 	["bright bronze", "shiny maroon"],
// 	["vibrant black", "muted gold", "striped red", "pale magenta", "clear violet"],
// 	["clear yellow", "plaid maroon"],
// 	["pale lavender", "shiny maroon", "bright cyan", "shiny orange", "striped tomato"],
// 	["dark chartreuse", "wavy brown"],
// 	["mirrored violet", "light lavender", "dull coral", "light red"],
// 	["vibrant beige", "shiny red", "clear tan"],
// 	["mirrored coral", "faded coral", "dull bronze"],
// 	["posh red", "wavy brown", "dark salmon", "dull chartreuse", "vibrant crimson"],
// 	["light green", "posh fuchsia"],
// 	["wavy green", "dark green", "posh chartreuse", "mirrored black"],
// 	["drab violet", "wavy yellow"],
// 	["dark crimson", "bright gray", "shiny violet", "pale chartreuse"],
// 	["posh green", "bright yellow", "faded yellow"],
// 	["shiny plum", "shiny indigo", "dark gold", "dim coral"],
// 	["striped beige", "muted beige"],
// 	["dark orange", "bright gold", "dotted maroon", "striped salmon", "vibrant red"],
// 	["bright orange", "muted blue", "striped blue", "dark cyan"],
// 	["dark black", "shiny lime", "clear olive", "dull bronze", "muted lavender"],
// 	["pale orange", "plaid violet", "shiny red", "dull coral", "shiny bronze"],
// 	["mirrored salmon", "vibrant red", "muted beige", "dark orange"],
// 	["drab yellow", "bright white"],
// 	["dull tomato", "muted beige", "posh salmon", "shiny maroon"],
// 	["striped fuchsia", "pale beige", "mirrored gray"],
// 	["mirrored beige", "mirrored black", "dim lavender", "clear lime"],
// 	["wavy tomato", "wavy fuchsia"],
// 	["bright indigo", "dull violet", "dull green", "dotted cyan", "dotted tan"],
// 	["striped blue", "posh red", "bright fuchsia", "dark aqua"],
// 	["bright green", "dim violet", "shiny coral", "dim white", "dim yellow"],
// 	["dotted salmon", "dull red", "striped salmon", "dotted maroon", "shiny red"],
// 	["light magenta", "dark fuchsia", "pale turquoise", "pale plum", "vibrant tan"],
// 	["mirrored olive", "shiny lavender"],
// 	["dark coral", "wavy teal", "muted plum"],
// 	["posh teal", "pale violet", "muted tan", "drab gray", "drab beige"],
// 	["bright teal", "mirrored coral"],
// 	["striped orange", "clear olive"],
// 	["faded plum", "striped black", "striped gold"],
// 	["plaid tomato", "muted salmon", "pale violet", "light violet", "dim tomato"],
// 	["dim blue", "drab salmon", "faded plum", "light salmon", "dark turquoise"],
// 	["striped coral", "wavy fuchsia"],
// 	["light violet", "dim beige", "striped lavender", "dotted orange", "wavy purple"],
// 	["dull white", "faded purple", "bright silver", "pale bronze", "clear fuchsia"],
// 	["dim white", "light yellow", "posh gold", "bright blue", "striped chartreuse"],
// 	["bright chartreuse", "muted gold", "dotted maroon"],
// 	["striped purple", "light orange", "dotted maroon", "dim magenta", "plaid violet"],
// 	["dotted tomato", "posh chartreuse"],
// 	["wavy lavender", "dim yellow", "pale turquoise", "vibrant red", "bright yellow"],
// 	["striped teal", "bright yellow"],
// 	["drab crimson", "wavy tan", "dull green", "muted blue"],
// 	["dull lime", "shiny tomato"],
// 	["posh salmon", "no other"],
// 	["vibrant aqua", "shiny indigo", "shiny crimson", "shiny cyan"],
// 	["drab black", "dull violet", "dotted maroon", "vibrant purple", "muted plum"],
// 	["drab olive", "drab orange", "dotted green", "drab chartreuse"],
// 	["dark plum", "dotted salmon", "wavy magenta", "bright chartreuse"],
// 	["plaid brown", "light lavender"],
// 	["striped magenta", "pale lime", "posh salmon", "clear tomato", "dull plum"],
// 	["dull orange", "light maroon"],
// 	["vibrant orange", "dull red", "posh chartreuse"],
// 	["mirrored turquoise", "drab cyan", "posh cyan", "clear gold", "plaid magenta"],
// 	["mirrored black", "no other"],
// 	["shiny black", "dotted green", "dim violet", "clear cyan", "muted fuchsia"],
// 	["vibrant indigo", "light maroon"],
// 	["bright fuchsia", "faded olive"],
// 	["dotted plum", "shiny violet"],
// 	["plaid lime", "bright gray", "pale beige", "light silver"],
// 	["plaid red", "shiny maroon", "striped lavender", "mirrored purple"],
// 	["mirrored lime", "faded coral", "dark gold", "mirrored indigo", "dull coral"],
// 	["drab lime", "dotted aqua", "shiny chartreuse"],
// 	["faded tan", "muted plum", "posh salmon"],
// 	["dark silver", "dotted maroon", "shiny white"],
// 	["striped indigo", "dull plum", "light lavender", "light red", "muted olive"],
// 	["bright gold", "no other"],
// 	["plaid black", "dull violet", "muted olive", "muted teal"],
// 	["dotted chartreuse", "no other"],
// 	["vibrant blue", "shiny cyan"],
// 	["dim indigo", "bright purple", "plaid magenta", "posh fuchsia", "plaid red"],
// 	["light red", "bright gold", "plaid silver", "dull violet", "pale turquoise"],
// 	["dim black", "dim orange", "dull lime", "faded indigo", "dotted olive"],
// 	["mirrored gold", "muted gold", "dark cyan"],
// 	["posh aqua", "clear violet"],
// 	["light blue", "drab chartreuse", "dull chartreuse"],
// 	["shiny maroon", "wavy violet"],
// 	["faded lavender", "dark salmon", "vibrant orange", "vibrant purple", "posh black"],
// 	["faded olive", "mirrored teal", "pale plum", "pale brown"],
// 	["drab indigo", "dim cyan", "plaid silver"],
// 	["clear white", "posh beige"],
// 	["wavy violet", "dotted fuchsia"],
// 	["dark turquoise", "vibrant turquoise", "vibrant lavender"],
// 	["striped violet", "mirrored turquoise", "muted orange", "dim teal", "posh green"],
// 	["wavy yellow", "dim yellow", "dim lavender"],
// 	["dark red", "striped gold", "vibrant tomato"],
// 	["plaid maroon", "light white", "plaid black"],
// 	["bright black", "light maroon", "shiny lime", "vibrant maroon", "clear violet"],
// 	["drab salmon", "clear coral", "dark indigo"],
// 	["plaid green", "pale indigo"],
// 	["pale teal", "drab black", "faded gray", "posh beige", "faded yellow"],
// 	["light silver", "bright yellow", "dim silver", "posh chartreuse"],
// 	["dull magenta", "posh turquoise", "light magenta", "shiny orange", "clear turquoise"],
// 	["pale white", "dark cyan"],
// 	["dull chartreuse", "mirrored black", "dotted salmon", "pale turquoise"],
// 	["dim salmon", "mirrored yellow", "striped salmon", "drab tomato", "dull yellow"],
// 	["shiny crimson", "faded tan", "muted salmon", "wavy teal", "vibrant orange"],
// 	["dark purple", "muted plum", "bright lavender", "dark cyan", "clear orange"],
// 	["clear brown", "dim orange", "vibrant maroon", "striped lime"],
// 	["muted silver", "vibrant gray"],
// 	["vibrant bronze", "posh red"],
// 	["mirrored maroon", "clear magenta", "posh brown", "wavy teal"],
// 	["muted tomato", "faded aqua", "wavy lavender", "mirrored silver"],
// 	["posh olive", "faded salmon", "muted green", "light tomato", "dark gold"],
// 	["dotted turquoise", "light orange", "dull brown"],
// 	["light bronze", "pale cyan", "shiny lime", "faded olive"],
// 	["striped gold", "muted salmon", "bright yellow", "dark plum", "light maroon"],
// 	["faded maroon", "wavy silver", "plaid magenta"],
// 	["clear magenta", "wavy turquoise"],
// 	["vibrant olive", "muted silver"],
// 	["clear tan", "mirrored gold"],
// 	["posh orange", "plaid blue", "dotted aqua"],
// 	["wavy cyan", "posh lavender"],
// 	["shiny chartreuse", "mirrored cyan", "posh chartreuse", "dotted aqua"],
// 	["light lime", "muted plum", "wavy purple"],
// 	["wavy silver", "faded lavender"],
// 	["drab red", "clear tomato", "pale turquoise", "dull yellow"],
// 	["light aqua", "dotted aqua"],
// 	["dim purple", "striped gold", "drab tan", "mirrored tan"],
// 	["shiny indigo", "pale magenta", "dim plum", "muted blue", "dim coral"],
// 	["pale lime", "mirrored cyan", "dull violet", "striped lime"],
// 	["posh lavender", "clear purple", "muted gold", "dull brown", "muted lime"],
// 	["dull lavender", "striped violet", "muted bronze"],
// 	["dotted lime", "plaid magenta", "plaid violet", "shiny lime", "plaid purple"],
// 	["posh coral", "mirrored violet", "clear violet", "dark fuchsia", "dotted silver"],
// 	["bright plum", "wavy brown"],
// 	["pale coral", "bright olive"],
// 	["dim fuchsia", "bright chartreuse", "mirrored teal", "posh salmon", "light chartreuse"],
// 	["dim cyan", "faded tan", "mirrored gold"],
// 	["faded cyan", "dotted black", "shiny maroon", "muted chartreuse"]
// ]

// //possible bags you can go into
// function possible_bags(_index){
// 	if (rules[_index][0] == "shiny gold") return 0
	
// 	for (var _i = 1; _i < array_length(rules[_index]); _i++){
// 		if (rules[_index][_i] == "shiny gold") return 1
// 	}
	
// 	var _ans = 0
	
// 	_ans += possible_bags()
	
// 	return _ans
// }

